### ISSUE TITLE
edit logo for our website

### ISSUE THREAD

**Issue by reveurguy** [Py-Contributors/py-contributors.github.io#20]
We need the logo edited for our website. We need the logo to be on a white circular background. The size can be between 50 * 50 and 80 * 80. You need to check the size with us before submitting, we will tell the size.

**Comment by aditimaurya** [comment]
@reveurguy  this seems an exciting issue, I'll surely design. Please assign me here.

**Comment by reveurguy** [comment]
@aditimaurya you can join the discord server and can send me the changes before making the pr.
**Discord** - https://discord.gg/jJCwJ6Q

**Comment by AmeyaJain-25** [comment]
@reveurguy 
I would like to make the changes as you wish to if the issue isn't solved yet.
If so, please assign me this issue

**Comment by reveurguy** [comment]
@AmeyaJain-25 currently aditi is working on it, but if there's any change i'll tell you. You can look into other repo's for issues to work on. And also the completed site will be displayed on the site in a couple of days, so you can create issues for any improvement or bugs.

**Comment by AmeyaJain-25** [comment]
Ok, No problem.
If the issue is not solved,
Please assign me the issue.

**Comment by reveurguy** [comment]
ok
