### ISSUE TITLE
enable pagination in updates/index.html

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/py-contributors.github.io#4]
Updates/index.html is for upcoming updates and blog using jekyll site generator.

enable pagination on that page.
`pagination : 5`
`paginate_path : "/updates/page:num"`

Reference :- https://jekyllrb.com/docs/pagination/

Check `CONTRIBUTING.md` files for more details. How to issue PR(Pull Request)

**Comment by ExpressHermes** [comment]
I would like to work on this.

**Comment by codeperfectplus** [comment]
Thanks for Considering the issue, do you have Discord so you can join for better communication because the website is in development mode.
Discord - soundsLikecrazy#9794

**Comment by ExpressHermes** [comment]
I have sent you request. My discord: ExpressHermes#3360

**Comment by codeperfectplus** [comment]
- [x] assigning the task to @ExpressHermes

**Comment by codeperfectplus** [comment]
Issue Solved
