### ISSUE TITLE
improve card in updates/index.html

### ISSUE THREAD

**Issue by DrakeEntity** [Py-Contributors/py-contributors.github.io#7]
Improve card Design for Better looks.
- Text alignment
- Picture alignment

**Comment by reveurguy** [comment]
what do you mean by improve? can you elaborate a bit.

**Comment by aditimaurya** [comment]
Hey, I would like to pick up this issue if you haven't assigned this to anyone. I would like to know more about this issue.

**Comment by reveurguy** [comment]
i would like to assign it to me. i have started and made some changes.

**Comment by codeperfectplus** [comment]
Thanks, both of you to take interest in contributing to py-contributors website.

This website is created with [jekyll](https://jekyllrb.com/). We are using `bootswatch(Bootstrap) cdn` for CSS and Js and Fontawesome for.

By improvement I mean 
- text alignment
- picture alignment
- etc with changing the main content.

@reveurguy 
You can find articles card in components/articles/ folder and can change the Homepage look.

Happy Coding,

**Comment by codeperfectplus** [comment]
@aditimaurya 
This updates page is designed for upcoming updates, projects idea etc. We don't have any content for sidebar yet.

You can check <https://py-contributors.github.io/updates/index.html>, we have cards here too.
Look whatever you can improve like changing `Read more` button location So it's looks better.

you can find post under /_post/ folder.

Happy Coding,

**Comment by reveurguy** [comment]
@codePerfectPlus are you on discord? so that i can run the changes by you.

**Comment by reveurguy** [comment]
and also i made changes to the the card on update page, so can i do both?
and also on the homepage can i change overall look also?

**Comment by reveurguy** [comment]
@codePerfectPlus can i connect with you on any social platform?
by any i mean insta, fb, discord.

**Comment by codeperfectplus** [comment]
@reveurguy 
- Discord - soundsLikecrazy#9794
- Telegram -https://t.me/pyContributors2

**Comment by aditimaurya** [comment]
@codePerfectPlus  May I know whether I'm eligible to work in that repository (you've mentioned in the above comments) or not as if @reveurguy  is doing the same then there would be confusions that who's PR you'll consider and all. So, would you please assign both the tasks to whom you wanted to. Do let me know if I could contribute in your projects anyhow. I'd love to do.  
Thanks !!!!

**Comment by codeperfectplus** [comment]
@reveurguy is working on homepage.

@aditimaurya You can improve updates/index.html.
I am creating a new issue and assigning you.

**Comment by aditimaurya** [comment]
Okay! Thanks a lot. :)
